CREATE TABLE public."Clientes" (
	"Documento" text NOT NULL,
	"RazaoSocial" text NOT NULL,
	"Logradouro" text NOT NULL,
	"Bairro" text NOT NULL,
	"Localidade" text NOT NULL,
	"Uf" text NOT NULL,
	"Cep" text NOT NULL,
	CONSTRAINT "PK_Clientes" PRIMARY KEY ("Documento")
);

CREATE TABLE public."Pedidos" (
	"IdPedido" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"IdProduto" int4 NOT NULL,
	"NumeroPedido" float4 NOT NULL,
	"DataEntrega" timestamptz NOT NULL,
	"Frete" float8 NOT NULL,
	CONSTRAINT "PK_Pedidos" PRIMARY KEY ("IdPedido")
);

ALTER TABLE public."Pedidos" ADD CONSTRAINT produtos_id_produto_fkey FOREIGN KEY ("IdProduto") REFERENCES public."Produtos"("IdProduto");

CREATE TABLE public."Produtos" (
	"IdProduto" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"TipoProduto" text NOT NULL,
	"Nome" text NOT NULL,
	"DocumentoCliente" text NOT NULL,
	"Valor" float8 NOT NULL,
	CONSTRAINT "PK_Produtos" PRIMARY KEY ("IdProduto")
);

ALTER TABLE public."Produtos" ADD CONSTRAINT produtos_documento_cliente_fkey FOREIGN KEY ("DocumentoCliente") REFERENCES public."Clientes"("Documento");

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO public."__EFMigrationsHistory"
("MigrationId", "ProductVersion")
VALUES('20231208203140_CriandoTabelasMigracao', '6.0.10');